version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fiber_app
    volumes:
      - ./:/app
    ports:
      - "${PORT:-8888}:8888"
    environment:
      - FIBER_ENV=production
      - PORT=${PORT:-8888}
    command: ["air", "-c", ".air/.air.toml"]
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - fiber_service

  postgres:
    image: postgres:latest
    container_name: fiber_postgres
    volumes:
      - ./docker/container_data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - fiber_service

networks:
  fiber_service:
    driver: bridge
