version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fiber_app
    volumes:
      - ./:/app
    ports:
      - "${PORT:-8888}:8888" 
    environment:
      - FIBER_ENV=production
      - PORT=${PORT:-8888}  
    command: ["air", "-c", ".air/.air.toml"] 
    env_file:
      - .env
