// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"golang-docker-demo/config"
)

// Injectors from wire.go:

func Ready() *DevServer {
	app := NewFiber()
	configConfig := config.NewConfig()
	devServer := NewDevServer(app, configConfig)
	return devServer
}
