// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"golang-docker-demo/app/modules/pet"
	"golang-docker-demo/config"
	"golang-docker-demo/db"
)

// Injectors from wire.go:

func Ready() *DevServer {
	app := NewFiber()
	configConfig := config.NewConfig()
	query := db.NewLocalQuery(configConfig)
	repositoryInterface := pet.NewRepository()
	useCaseInterface := pet.NewUseCase(query, repositoryInterface)
	api := NewApi(useCaseInterface)
	devServer := NewDevServer(app, configConfig, api)
	return devServer
}
