# research/.air/.air.toml

# Config file for air
root = "."
tmp_dir = ".air"
[build]
    cmd = "go build -o ./.air/main ." 
    bin = "./.air/main"              
    full_bin = "APP_ENV=dev ./.air/main"
    watch_dir = ["./"]
    exclude_dir = ["vendor", ".air"]
    include_ext = ["go", "tpl", "html"]
    exclude_ext = ["swp", "log"]
    delay = 1000
    stop_on_error = true
